/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const alertPropDocs: GeneratedComponentDoc = {
  "name": "Alert",
  "interfaceName": "AlertProps",
  "description": "",
  "sourcePath": "src\\components\\Alert\\Alert.types.ts",
  "props": [
    {
      "name": "actions",
      "type": "ReactNode",
      "description": "Action content rendered by the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "actionsClassName",
      "type": "string",
      "description": "Additional CSS class names for the actions section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Content rendered inside the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional CSS class names for the content section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "dismissButtonClassName",
      "type": "string",
      "description": "Additional CSS class names for the dismiss button section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "dismissible",
      "type": "boolean",
      "description": "Dismissible.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "dismissLabel",
      "type": "string",
      "description": "Dismiss Label.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Dismiss alert\""
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Glass.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "icon",
      "type": "ReactNode",
      "description": "Icon rendered by the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Additional CSS class names for the icon section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "messageClassName",
      "type": "string",
      "description": "Additional CSS class names for the message section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onDismiss",
      "type": "(() => void)",
      "description": "Callback fired when dismiss occurs.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Outline.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "false"
    },
    {
      "name": "role",
      "type": "\"status\" | \"alert\" | \"note\"",
      "description": "Role.",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "state === \"error\" ? \"alert\" : \"status\""
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state applied to the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "description": "Title content rendered by the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleClassName",
      "type": "string",
      "description": "Additional CSS class names for the title section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "AlertVariant",
      "description": "Variant.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"solid\""
    }
  ]
};
