/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const appShellPropDocs: GeneratedComponentDoc = {
  "name": "AppShell",
  "interfaceName": "AppShellProps",
  "description": "Props for the AppShell component.",
  "sourcePath": "src\\components\\AppShell\\AppShell.types.ts",
  "props": [
    {
      "name": "aside",
      "type": "ReactNode",
      "description": "Complementary aside region rendered after the main content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "asideWidth",
      "type": "string",
      "description": "Width of the aside column.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"18rem\""
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Main page content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root shell.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class name for the main content area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the shell is visually disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "footer",
      "type": "ReactNode",
      "description": "Footer region rendered below the main content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Whether to render glass styling.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "header",
      "type": "ReactNode",
      "description": "Header region rendered at the top of the shell.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Legacy alias for header content retained for scaffold compatibility.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the shell should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "mainClassName",
      "type": "string",
      "description": "Additional class name for the main content region.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to render outlined styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "sidebar",
      "type": "ReactNode",
      "description": "Navigation/sidebar region rendered before the main content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "sidebarCollapsed",
      "type": "boolean",
      "description": "Whether the sidebar column should be present but collapsed.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "sidebarWidth",
      "type": "string",
      "description": "Width of the sidebar column.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"16rem\""
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "stickyHeader",
      "type": "boolean",
      "description": "Whether the header should stick to the top of the viewport.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"app-shell\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    }
  ]
};
