/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const avatarPropDocs: GeneratedComponentDoc = {
  "name": "Avatar",
  "interfaceName": "AvatarProps",
  "description": "Props for the Avatar component.",
  "sourcePath": "src\\components\\Avatar\\Avatar.types.ts",
  "props": [
    {
      "name": "alt",
      "type": "string",
      "description": "Alternative text for the avatar image. Used as the image alt text and may also contribute to the accessible name.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-current",
      "type": "boolean | \"page\" | \"step\" | \"location\" | \"date\" | \"time\"",
      "description": "Indicates the current state or item within a set when the avatar acts as a link. Example: page, step, location, date, time, true.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References the element(s) that describe the avatar with additional context. Useful for status, activity, or profile details.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Explicit accessible name for the interactive avatar element. Overrides inferred labels such as label, alt, or name.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References the element(s) that label the avatar. Should take precedence over aria-label when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Custom child elements (replaces avatar content entirely).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Custom class names for the avatar container.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"\""
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Disables interaction and styles as disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "fallback",
      "type": "ReactNode",
      "description": "Custom fallback content (overrides initials).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Applies a translucent frosted-glass treatment using the active theme palette.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "href",
      "type": "string",
      "description": "If provided, avatar becomes a link (internal or external).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "imageFill",
      "type": "boolean",
      "description": "If true, passes a `fill` prop to a custom image component such as Next.js Image. Plain img rendering should leave this false.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Visible or semantic label for the avatar. Used as a fallback accessible name when aria-label / aria-labelledby are not provided.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Full name used to generate initials when no image is available.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"\""
    },
    {
      "name": "onClick",
      "type": "((e: MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => void)",
      "description": "Click handler (used only when not a link).",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to apply an outline style.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "priority",
      "type": "boolean",
      "description": "If true, the image loads with higher priority.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rel",
      "type": "string",
      "description": "Optional rel attribute when the avatar renders as a link.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "AriaRole",
      "description": "Optional role override for custom avatar rendering patterns. In most cases this should be left undefined so the native button/link role is preserved.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the avatar ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "shape",
      "type": "ShapeType",
      "description": "Shape of the avatar border ('circle' | 'square' | 'rounded').",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"circle\""
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the avatar ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "src",
      "type": "string",
      "description": "Optional image URL for avatar display.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the avatar ('success' | 'error' | 'warning').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"\""
    },
    {
      "name": "status",
      "type": "StatusType",
      "description": "Optional status indicator for user availability and activity. ( \"online\" | \"offline\" | \"away\" | \"busy\") Useful for chat apps, collaboration tools, or profile displays.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "statusIcon",
      "type": "ReactNode",
      "description": "Custom icon to replace the default status dot.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "statusLabel",
      "type": "string",
      "description": "Optional accessible label for the status indicator. Example: \"Online\", \"Busy\", or \"In a meeting\". Helpful when the status conveys important information not otherwise described nearby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "statusPosition",
      "type": "StatusPositionType",
      "description": "Position of the status indicator dot/icon ('topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight').",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"bottomRight\""
    },
    {
      "name": "target",
      "type": "React.HTMLAttributeAnchorTarget",
      "description": "Optional target attribute when the avatar renders as a link.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"avatar\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Visual theme of the avatar ('primary', 'secondary', 'tertiary', 'quaternary', 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    }
  ]
};
