/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const badgePropDocs: GeneratedComponentDoc = {
  "name": "Badge",
  "interfaceName": "BadgeProps",
  "description": "Props for the Badge component.",
  "sourcePath": "src\\components\\Badge\\Badge.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Optional custom badge content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional custom class names.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "If true, disables user interaction and styles as disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Applies a translucent frosted-glass treatment using the active theme palette.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "href",
      "type": "string",
      "description": "Optional href. When provided, the badge renders as an anchor link.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "icon",
      "type": "IconType",
      "description": "Optional icon to render inside the badge.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onClick",
      "type": "((e: MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => void)",
      "description": "Click handler for the badge.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to use the outline style.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "rel",
      "type": "string",
      "description": "Optional rel attribute when the badge renders as a link.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the badge ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the badge ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Badge size ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "The badge state ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "target",
      "type": "React.HTMLAttributeAnchorTarget",
      "description": "Optional target attribute when the badge renders as a link.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"badge\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme color for the badge ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Optional tooltip shown on hover.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
