/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const barChartPropDocs: GeneratedComponentDoc = {
  "name": "BarChart",
  "interfaceName": "BarChartProps",
  "description": "Props for the BarChart component.",
  "sourcePath": "src/components/BarChart/BarChart.types.ts",
  "props": [
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the chart graphic.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data",
      "type": "ChartDatum[]",
      "description": "Labelled values rendered as vertical bars.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "gap",
      "type": "number",
      "description": "Gap between bars in SVG units.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "8"
    },
    {
      "name": "height",
      "type": "number",
      "description": "Height of the SVG viewport.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "180"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible chart label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "padding",
      "type": "number",
      "description": "Inner SVG padding.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "24"
    },
    {
      "name": "showGrid",
      "type": "boolean",
      "description": "Whether to render horizontal guide lines.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "showLabels",
      "type": "boolean",
      "description": "Whether to render category labels below bars.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"bar-chart\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"primary\""
    },
    {
      "name": "units",
      "type": "string",
      "description": "Optional unit label shown beside formatted values.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "valueFormatter",
      "type": "ChartValueFormatter",
      "description": "Formatter used for visible and accessible values.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "formatDefaultValue"
    },
    {
      "name": "width",
      "type": "number",
      "description": "Width of the SVG viewport.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "320"
    }
  ]
};
