/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const bentoBoxPropDocs: GeneratedComponentDoc = {
  "name": "BentoBox",
  "interfaceName": "BentoBoxProps",
  "description": "",
  "sourcePath": "src/components/Layout/Layout.types.ts",
  "props": [
    {
      "name": "align",
      "type": "LayoutAlign",
      "description": "Align prop for LayoutPrimitive.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "as",
      "type": "ElementType",
      "description": "As prop for LayoutPrimitive.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Content rendered inside the component.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for the component root.",
      "required": false,
      "inherited": true,
      "category": "styling"
    },
    {
      "name": "columns",
      "type": "BentoBoxColumns",
      "description": "Number of columns at wide container sizes.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "4"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": true,
      "category": "testing"
    },
    {
      "name": "dense",
      "type": "boolean",
      "description": "Backfills open cells when possible. Keep this off when visual order must match reading and focus order.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "gap",
      "type": "LayoutGap",
      "description": "Gap.",
      "required": false,
      "inherited": true,
      "category": "props",
      "defaultValue": "\"md\""
    },
    {
      "name": "gridClassName",
      "type": "string",
      "description": "Additional class name for the internal grid.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "justify",
      "type": "LayoutJustify",
      "description": "Justify prop for LayoutPrimitive.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "minRowHeight",
      "type": "string",
      "description": "Minimum height used by each implicit grid row.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"8rem\""
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": true,
      "category": "props"
    }
  ]
};
