/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const bentoBoxItemPropDocs: GeneratedComponentDoc = {
  "name": "BentoBoxItem",
  "interfaceName": "BentoBoxItemProps",
  "description": "",
  "sourcePath": "src/components/Layout/Layout.types.ts",
  "props": [
    {
      "name": "as",
      "type": "ElementType",
      "description": "As prop for LayoutPrimitive.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Content rendered inside the component.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for the component root.",
      "required": false,
      "inherited": true,
      "category": "styling"
    },
    {
      "name": "columnSpan",
      "type": "BentoBoxColumnSpan",
      "description": "Number of columns occupied at wide container sizes.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "1"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": true,
      "category": "testing"
    },
    {
      "name": "rowSpan",
      "type": "BentoBoxColumns",
      "description": "Number of rows occupied at wide container sizes.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "1"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": true,
      "category": "props"
    }
  ]
};
