/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const circularProgressPropDocs: GeneratedComponentDoc = {
  "name": "CircularProgress",
  "interfaceName": "CircularProgressProps",
  "description": "Props for the CircularProgress component.",
  "sourcePath": "src\\components\\CircularProgress\\CircularProgress.types.ts",
  "props": [
    {
      "name": "announceInnerValue",
      "type": "boolean",
      "description": "Whether the visible value text inside the circle should be announced by assistive technologies. Default: false, because the progressbar itself already exposes value via ARIA.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID reference to one or more elements that describe the progressbar.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the progressbar. Takes priority over `label`.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID reference to one or more elements that label the progressbar. Takes priority over `aria-label` and `label`.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "ariaValueText",
      "type": "string",
      "description": "Custom accessible value text for assistive technologies. Example: \"75 percent complete\"",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "decorative",
      "type": "boolean",
      "description": "Marks the component as decorative. When true, the progressbar will be hidden from assistive technology.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Applies a translucent frosted-glass treatment using the active theme palette.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Visible label fallback and default accessible name. Used only when no aria-label or aria-labelledby is provided.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Progress\""
    },
    {
      "name": "max",
      "type": "number",
      "description": "Maximum value for the range (default: 100).",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "100"
    },
    {
      "name": "min",
      "type": "number",
      "description": "Minimum value for the range (default: 0).",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "0"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Optional shadow style for the component ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "showRaw",
      "type": "boolean",
      "description": "Whether to show raw value (e.g., \"75/100\") instead of percent.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the component ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of progress ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"circular-progress\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Optional theme for the component ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "units",
      "type": "string",
      "description": "Optional unit label shown beside raw values.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "value",
      "type": "number",
      "description": "Current value to be visualized (e.g., 75).",
      "required": true,
      "inherited": false,
      "category": "props"
    }
  ]
};
