/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const colorPickerPropDocs: GeneratedComponentDoc = {
  "name": "ColorPicker",
  "interfaceName": "ColorPickerProps",
  "description": "Props for the ColorPicker component.",
  "sourcePath": "src/components/ColorPicker/ColorPicker.types.ts",
  "props": [
    {
      "name": "allowCustom",
      "type": "boolean",
      "description": "If true, allows picking a custom color via a color input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References one or more elements that describe the group. This will be merged with helperText / errorText IDs when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible name for the group when no visible label should be used or when a more descriptive label is needed.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References an external element that labels the group. Prefer this when the visible label exists outside the component.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Custom class name for the component container.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "colors",
      "type": "ColorOption[]",
      "description": "Array of color options to choose from.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "customInputAriaLabel",
      "type": "string",
      "description": "Optional label for the custom color input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Custom color picker\""
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the entire picker is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "errorMessage",
      "type": "string",
      "description": "Optional error message shown when invalid.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperText",
      "type": "string",
      "description": "Optional helper text shown below or associated with the picker.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "hideLabel",
      "type": "boolean",
      "description": "Hide the visible legend visually while preserving it for screen readers.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "Marks the group as invalid.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Optional visible label above the color group.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Choose a color\""
    },
    {
      "name": "name",
      "type": "string",
      "description": "Optional name attribute for the radio group.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"color-picker\""
    },
    {
      "name": "onValueChange",
      "type": "(color: string) => void",
      "description": "Callback triggered when a color is value.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Marks the group as required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Applies a shadow effect to the swatches ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "shape",
      "type": "ShapeType",
      "description": "Shape of the swatches ('square' | 'round' | 'pill').",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"round\""
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"color-picker\""
    },
    {
      "name": "value",
      "type": "string",
      "description": "Currently value color value.",
      "required": true,
      "inherited": false,
      "category": "props"
    }
  ]
};
