/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const comboBoxPropDocs: GeneratedComponentDoc = {
  "name": "ComboBox",
  "interfaceName": "ComboBoxProps",
  "description": "",
  "sourcePath": "src\\components\\ComboBox\\ComboBox.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ARIA Describedby attribute forwarded to the relevant accessible element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "ARIA Label attribute forwarded to the relevant accessible element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ARIA Labelledby attribute forwarded to the relevant accessible element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the component is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "emptyMessage",
      "type": "ReactNode",
      "description": "Empty Message.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"No options found\""
    },
    {
      "name": "error",
      "type": "ReactNode",
      "description": "Error message or error state displayed with the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorClassName",
      "type": "string",
      "description": "Additional CSS class names for the error section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Glass.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "Helper text displayed with the field.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperTextClassName",
      "type": "string",
      "description": "Additional CSS class names for the helper text section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "HTML id applied to the relevant element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputClassName",
      "type": "string",
      "description": "Additional CSS class names for the input section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputValue",
      "type": "string",
      "description": "Current text input value.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible label content for the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional CSS class names for the label section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Label Position.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "layoutClassName",
      "type": "string",
      "description": "Additional CSS class names for the layout section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "listboxClassName",
      "type": "string",
      "description": "Additional CSS class names for the listbox section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Loading.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "loadingMessage",
      "type": "ReactNode",
      "description": "Loading Message.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Loading options\""
    },
    {
      "name": "name",
      "type": "string",
      "description": "HTML name applied to the relevant form element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((value: string, option: ComboBoxOption) => void)",
      "description": "Callback fired when change occurs.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onInputChange",
      "type": "((value: string) => void)",
      "description": "Callback fired when input change occurs.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "optionClassName",
      "type": "string",
      "description": "Additional CSS class names for the option section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "options",
      "type": "ComboBoxOption[]",
      "description": "Options available for selection.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Outline.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Placeholder.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Search options\""
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Current value for the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
