/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const dataTablePropDocs: GeneratedComponentDoc = {
  "name": "DataTable",
  "interfaceName": "DataTableProps",
  "description": "Props for the DataTable component.",
  "sourcePath": "src/components/DataTable/DataTable.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Accessible description reference for the table. Useful for tying helper or instructional text to the table.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for screen readers. Use this when there is no visible caption or heading tied to the table.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible labelledby reference for the table. Prefer this when a visible heading already labels the table.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "bulkActions",
      "type": "((selectedKeys: Array<string | number>, selectedRows: T[]) => ReactNode)",
      "description": "Optional actions shown only when one or more rows are selected.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "bulkToolbarClassName",
      "type": "string",
      "description": "Optional class name for the bulk action toolbar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "caption",
      "type": "string",
      "description": "Optional visible or screen-reader-only caption text for the table. A table caption is the preferred built-in table label.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Data table\""
    },
    {
      "name": "cellClassName",
      "type": "((value: unknown, row: T, column: Column<T>, rowIndex: number) => string)",
      "description": "Optional dynamic class name for each cell.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for the table wrapper.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "colCount",
      "type": "number",
      "description": "Total column count override. Helpful when rendering dynamic or grouped columns in advanced cases.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "columnMenuClassName",
      "type": "string",
      "description": "Optional class name for the column visibility menu.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "columnOrder",
      "type": "(keyof T)[]",
      "description": "Controlled column order.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "columnPinning",
      "type": "boolean",
      "description": "Enables column pin/unpin controls.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "columnReorder",
      "type": "boolean",
      "description": "Enables keyboard/button column reordering controls in each header.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "columnResize",
      "type": "boolean",
      "description": "Enables column resizing controls.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "columnVisibility",
      "type": "boolean",
      "description": "Enables the column visibility menu.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "columnWidths",
      "type": "Partial<Record<keyof T, string>>",
      "description": "Controlled column widths keyed by column key.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "columns",
      "type": "Column<T>[]",
      "description": "Array of column definitions.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "currentPage",
      "type": "number",
      "description": "Controlled current page, 1-indexed.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data",
      "type": "T[]",
      "description": "Array of row data objects.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultColumnOrder",
      "type": "(keyof T)[]",
      "description": "Initial column order for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "defaultColumnWidths",
      "type": "Partial<Record<keyof T, string>>",
      "description": "Initial column widths for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "{}"
    },
    {
      "name": "defaultExpandedRowKeys",
      "type": "(string | number)[]",
      "description": "Initial expanded row keys for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "defaultFilterValue",
      "type": "string",
      "description": "Initial filter query for uncontrolled filtering.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "defaultPage",
      "type": "number",
      "description": "Initial page for uncontrolled pagination.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "1"
    },
    {
      "name": "defaultPinnedColumnKeys",
      "type": "(keyof T)[]",
      "description": "Initial pinned column keys for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "defaultSelectedRowKeys",
      "type": "(string | number)[]",
      "description": "Initial selected row keys for uncontrolled selection.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "defaultSortKey",
      "type": "keyof T",
      "description": "Default key to sort by on initial render.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "defaultSortOrder",
      "type": "\"desc\" | \"asc\"",
      "description": "Default sort order on initial render ('asc' | 'desc').",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"asc\""
    },
    {
      "name": "defaultVisibleColumnKeys",
      "type": "(keyof T)[]",
      "description": "Initial visible column keys for uncontrolled column visibility.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "emptyMessage",
      "type": "string",
      "description": "Text shown when no rows are available.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"No data available\""
    },
    {
      "name": "expandedRowKeys",
      "type": "(string | number)[]",
      "description": "Controlled expanded row keys.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "filterAriaLabel",
      "type": "string",
      "description": "Accessible label for the filter input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Filter table rows\""
    },
    {
      "name": "filterInputClassName",
      "type": "string",
      "description": "Optional class name for the filter input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "filterPlaceholder",
      "type": "string",
      "description": "Placeholder for the filter input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Filter table\""
    },
    {
      "name": "filterValue",
      "type": "string",
      "description": "Controlled filter query.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "filterable",
      "type": "boolean",
      "description": "Enables the built-in client-side filter input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "getRowAriaDescription",
      "type": "((row: T, index: number) => string)",
      "description": "Optional row description for screen readers. Only used when rows are interactive.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getRowAriaLabel",
      "type": "((row: T, index: number) => string)",
      "description": "Optional accessible label for interactive rows. Only used when onRowClick is provided.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getRowSelectAriaLabel",
      "type": "((row: T, index: number) => string)",
      "description": "Accessible label for a row selection checkbox.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getSortAnnouncement",
      "type": "((column: Column<T>, sortOrder: \"asc\" | \"desc\") => string)",
      "description": "Live region text announced when sorting changes. Receives the active column and current order.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getSortAriaLabel",
      "type": "((column: Column<T>, sortOrder: \"asc\" | \"desc\", isActive: boolean) => string)",
      "description": "Accessible label for the sort buttons/controls. Receives the column label and current sort order.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "hideCaption",
      "type": "boolean",
      "description": "Whether the caption should be visually hidden. Useful when you want semantic labeling without visible UI.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "itemsPerPage",
      "type": "number",
      "description": "Rows displayed on each page.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "10"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the table is currently loading data.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "loadingMessage",
      "type": "string",
      "description": "Accessible and/or visible loading message.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Loading data\""
    },
    {
      "name": "onCellEdit",
      "type": "((value: unknown, meta: DataTableCellEditMeta<T>) => void)",
      "description": "Callback fired when an editable cell commits a value.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onColumnOrderChange",
      "type": "((keys: Array<keyof T>) => void)",
      "description": "Callback fired when column order changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onColumnVisibilityChange",
      "type": "((keys: Array<keyof T>) => void)",
      "description": "Callback fired when visible columns change.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onColumnWidthsChange",
      "type": "((widths: Partial<Record<keyof T, string>>) => void)",
      "description": "Callback fired when column widths change.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onExpandedRowsChange",
      "type": "((keys: Array<string | number>, rows: T[]) => void)",
      "description": "Callback fired when expanded rows change.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onFilterChange",
      "type": "((value: string) => void)",
      "description": "Callback fired when the filter query changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onPageChange",
      "type": "((page: number, meta: DataTablePageChangeMeta) => void)",
      "description": "Callback fired when the page changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onPinnedColumnKeysChange",
      "type": "((keys: Array<keyof T>) => void)",
      "description": "Callback fired when pinned columns change.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onRowClick",
      "type": "((row: T) => void)",
      "description": "Optional callback when a row is clicked.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onSelectionChange",
      "type": "((selectedKeys: Array<string | number>, selectedRows: T[]) => void)",
      "description": "Callback fired when row selection changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onSortChange",
      "type": "((key: keyof T, order: \"asc\" | \"desc\") => void)",
      "description": "Function to handle server-side sorting.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "pagination",
      "type": "boolean",
      "description": "Enables built-in client-side pagination controls.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "paginationClassName",
      "type": "string",
      "description": "Optional class name for the pagination footer.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "pinnedColumnKeys",
      "type": "(keyof T)[]",
      "description": "Controlled pinned column keys.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "renderExpandedRow",
      "type": "((row: T, index: number) => ReactNode)",
      "description": "Render expanded content for a row. Enables row expansion controls.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the table ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "rowClassName",
      "type": "string | ((row: T, index: number) => string)",
      "description": "Optional static or dynamic class name for each row.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rowCount",
      "type": "number",
      "description": "Total row count override. Helpful for virtualized or server-paginated tables.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rowKey",
      "type": "((row: T) => string | number)",
      "description": "Function to derive a unique key for each row.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "selectAllAriaLabel",
      "type": "string",
      "description": "Accessible label for the select-all checkbox.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Select all rows\""
    },
    {
      "name": "selectableRows",
      "type": "boolean",
      "description": "Enables checkbox row selection.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "selectedRowKeys",
      "type": "(string | number)[]",
      "description": "Controlled selected row keys.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "serverPagination",
      "type": "boolean",
      "description": "Enables server-side pagination. The table will not slice data locally.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "serverSort",
      "type": "boolean",
      "description": "Whether to enable server-side sorting.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the data table ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the table ('success' | 'error' | 'warning' | 'info' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "striped",
      "type": "boolean",
      "description": "Whether to use striped row styling.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "tableClassName",
      "type": "string",
      "description": "Optional class name applied directly to the table element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "tbodyClassName",
      "type": "string",
      "description": "Optional class name applied to the table body.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"data-table\""
    },
    {
      "name": "theadClassName",
      "type": "string",
      "description": "Optional class name applied to the table head.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling the table ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "toolbarActions",
      "type": "ReactNode",
      "description": "Optional actions rendered in the table toolbar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "toolbarClassName",
      "type": "string",
      "description": "Optional class name for the toolbar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "toolbarTitle",
      "type": "ReactNode",
      "description": "Optional toolbar title shown above the table.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "totalItems",
      "type": "number",
      "description": "Total rows for server-side pagination. Falls back to the processed row count.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    },
    {
      "name": "virtualOverscan",
      "type": "number",
      "description": "Extra rows rendered before and after the visible virtualized range.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "4"
    },
    {
      "name": "virtualRowHeight",
      "type": "number",
      "description": "Estimated/fixed row height used by the virtualized renderer.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "48"
    },
    {
      "name": "virtualViewportHeight",
      "type": "number",
      "description": "Height of the virtualized viewport.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "360"
    },
    {
      "name": "virtualized",
      "type": "boolean",
      "description": "Enables row virtualization for large client-side data sets.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "visibleColumnKeys",
      "type": "(keyof T)[]",
      "description": "Controlled list of visible column keys.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "wrapCells",
      "type": "boolean",
      "description": "Allows table cells to wrap onto multiple lines. Can be overridden per column with column.wrap.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    }
  ]
};
