/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const datePickerPropDocs: GeneratedComponentDoc = {
  "name": "DatePicker",
  "interfaceName": "DatePickerProps",
  "description": "Props for the DatePicker component.",
  "sourcePath": "src\\components\\DatePicker\\DatePicker.types.ts",
  "props": [
    {
      "name": "autoComplete",
      "type": "React.HTMLInputAutoCompleteAttribute",
      "description": "Optional autocomplete value.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"off\""
    },
    {
      "name": "buttonClassName",
      "type": "string",
      "description": "Additional class name for the picker trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class name for the outer label/component container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultValue",
      "type": "string",
      "description": "Initial date value in YYYY-MM-DD format for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "description",
      "type": "ReactNode",
      "description": "Supporting description connected with aria-describedby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "descriptionClassName",
      "type": "string",
      "description": "Additional class name for description text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the component is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "error",
      "type": "ReactNode",
      "description": "Error text connected with aria-errormessage and announced as an alert.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorClassName",
      "type": "string",
      "description": "Additional class name for error text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "description": "Whether the picker should stretch to the full available width.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Whether to render glass styling.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "Helper text connected with aria-describedby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperTextClassName",
      "type": "string",
      "description": "Additional class name for helper text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputClassName",
      "type": "string",
      "description": "Additional class name for the native input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputWrapperClassName",
      "type": "string",
      "description": "Additional class name for the input/button wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Optional visible label for the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the component.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "max",
      "type": "string",
      "description": "Maximum selectable date in YYYY-MM-DD format.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "min",
      "type": "string",
      "description": "Minimum selectable date in YYYY-MM-DD format.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Name attribute used for form submission.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((value: string) => void)",
      "description": "Callback fired when the date value changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to render outlined styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "pickerButtonAriaLabel",
      "type": "string",
      "description": "Accessible label for the picker trigger button.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Open date picker\""
    },
    {
      "name": "pickerButtonTitle",
      "type": "string",
      "description": "Optional title for the picker trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Optional placeholder text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "description": "Whether the input is read-only.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the input is required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"date-picker\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Optional input title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Current date value in YYYY-MM-DD format.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
