/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const dateTimePickerPropDocs: GeneratedComponentDoc = {
  "name": "DateTimePicker",
  "interfaceName": "DateTimePickerProps",
  "description": "Props for the DateTimePicker component.",
  "sourcePath": "src\\components\\DateTimePicker\\DateTimePicker.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Accessible description reference for the input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-errormessage",
      "type": "string",
      "description": "Accessible error message reference for the input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "description": "Marks the input as invalid. Useful for external validation control.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the input when no visible label is present or when an override is needed.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible label reference for the input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "description": "Marks the input as required for assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "autoComplete",
      "type": "React.HTMLInputAutoCompleteAttribute",
      "description": "Optional autocomplete value.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"off\""
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"\""
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "descriptionId",
      "type": "string",
      "description": "Custom id for helper/description text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the input is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "errorId",
      "type": "string",
      "description": "Custom id for error text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Adds translucent glass styling to the input surface.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Custom input id.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Optional visible label displayed above the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelId",
      "type": "string",
      "description": "Custom label id.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "max",
      "type": "string",
      "description": "Maximum allowed date/time (ISO 8601 format).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "min",
      "type": "string",
      "description": "Minimum allowed date/time (ISO 8601 format).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Name attribute for form submission.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((newValue: string) => void)",
      "description": "Callback triggered when the date/time value changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to use outlined styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "pickerButtonAriaDescribedBy",
      "type": "string",
      "description": "Accessible description reference for the calendar trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "pickerButtonAriaLabel",
      "type": "string",
      "description": "Accessible label for the calendar trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "pickerButtonAriaLabelledBy",
      "type": "string",
      "description": "Accessible label reference for the calendar trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "pickerButtonTitle",
      "type": "string",
      "description": "Optional title/tooltip for the picker trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Optional placeholder text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "description": "Whether the input should be read-only.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the input is required for form validation.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Controls the rounding of the input ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Controls the shadow of the input ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the component ('xs' | 'small' | 'medium' | 'large' | 'xl').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the input ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"\""
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"datetime-picker\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Thematic style of the input ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Optional title/tooltip for the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Current value in ISO 8601 format (e.g., \"2025-04-10T12:00\").",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
