/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const donutChartPropDocs: GeneratedComponentDoc = {
  "name": "DonutChart",
  "interfaceName": "DonutChartProps",
  "description": "Props for the DonutChart component.",
  "sourcePath": "src/components/DonutChart/DonutChart.types.ts",
  "props": [
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the chart graphic.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "centerLabel",
      "type": "ReactNode",
      "description": "Content rendered in the center of the donut.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data",
      "type": "ChartDatum[]",
      "description": "Labelled values rendered as donut segments.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible chart label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "showLegend",
      "type": "boolean",
      "description": "Whether to show a generated legend below the chart.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "size",
      "type": "number",
      "description": "Width and height of the SVG viewport.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "180"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"donut-chart\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"primary\""
    },
    {
      "name": "thickness",
      "type": "number",
      "description": "Donut segment thickness.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "28"
    },
    {
      "name": "units",
      "type": "string",
      "description": "Optional unit label shown beside formatted values.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "valueFormatter",
      "type": "ChartValueFormatter",
      "description": "Formatter used for visible and accessible values.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "formatDefaultValue"
    }
  ]
};
