/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const drawerPropDocs: GeneratedComponentDoc = {
  "name": "Drawer",
  "interfaceName": "DrawerProps",
  "description": "",
  "sourcePath": "src/components/Drawer/Drawer.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ARIA Describedby attribute forwarded to the relevant accessible element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "ARIA Label attribute forwarded to the relevant accessible element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ARIA Labelledby attribute forwarded to the relevant accessible element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "bodyClassName",
      "type": "string",
      "description": "Additional CSS class names for the body section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Content rendered inside the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "closeButtonAriaLabel",
      "type": "string",
      "description": "Close Button Aria Label.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Close drawer\""
    },
    {
      "name": "closeButtonClassName",
      "type": "string",
      "description": "Additional CSS class names for the close button section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "closeOnEscape",
      "type": "boolean",
      "description": "Close On Escape.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "closeOnOverlayClick",
      "type": "boolean",
      "description": "Close On Overlay Click.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "footer",
      "type": "ReactNode",
      "description": "Custom footer content rendered by the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerClassName",
      "type": "string",
      "description": "Additional CSS class names for the footer section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "header",
      "type": "ReactNode",
      "description": "Custom header content rendered by the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "headerClassName",
      "type": "string",
      "description": "Additional CSS class names for the header section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "description": "Callback fired when close occurs.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "open",
      "type": "boolean",
      "description": "Open.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "overlayClassName",
      "type": "string",
      "description": "Additional CSS class names for the overlay section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "panelClassName",
      "type": "string",
      "description": "Additional CSS class names for the panel section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "placement",
      "type": "DrawerPlacement",
      "description": "Placement.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"right\""
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state applied to the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "description": "Title content rendered by the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleClassName",
      "type": "string",
      "description": "Additional CSS class names for the title section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
