/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const fieldSetPropDocs: GeneratedComponentDoc = {
  "name": "FieldSet",
  "interfaceName": "FieldSetProps",
  "description": "Props for the FieldSet component.",
  "sourcePath": "src/components/FieldSet/FieldSet.types.ts",
  "props": [
    {
      "name": "actions",
      "type": "ReactNode",
      "description": "Optional actions rendered in the fieldset footer.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "actionsClassName",
      "type": "string",
      "description": "Additional class name for the actions area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "bodyClassName",
      "type": "string",
      "description": "Additional class name for the grouped control body.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Main content rendered inside the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class name for the outer label/component container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class name for the content area. Alias for bodyClassName.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "descriptionClassName",
      "type": "string",
      "description": "Additional class name for the description text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the component is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "errorClassName",
      "type": "string",
      "description": "Additional class name for error text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorMessage",
      "type": "ReactNode",
      "description": "Error message rendered after the grouped controls and announced to assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footer",
      "type": "ReactNode",
      "description": "Optional footer content rendered after helper and error text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerClassName",
      "type": "string",
      "description": "Additional class name for the footer area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "Supporting text rendered after the grouped controls.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperTextClassName",
      "type": "string",
      "description": "Additional class name for helper text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "hideLegend",
      "type": "boolean",
      "description": "Whether the legend should remain available to assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Backward-compatible alias for the component legend.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the component.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "layout",
      "type": "FieldSetLayoutType",
      "description": "Layout used for the grouped controls.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"stack\""
    },
    {
      "name": "legend",
      "type": "ReactNode",
      "description": "Semantic legend for the grouped controls.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "legendClassName",
      "type": "string",
      "description": "Additional class name for the semantic legend.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "loadingMessage",
      "type": "ReactNode",
      "description": "Accessible loading message rendered while loading is true.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Loading\""
    },
    {
      "name": "optionalText",
      "type": "ReactNode",
      "description": "Optional text rendered next to the legend when required is false.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the field group is required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "requiredIndicator",
      "type": "ReactNode",
      "description": "Text or marker rendered next to the legend when required is true.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"*\""
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "spacing",
      "type": "FieldSetSpacingType",
      "description": "Spacing used between grouped controls.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"md\""
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"field-set\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
