/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const fileUploadPropDocs: GeneratedComponentDoc = {
  "name": "FileUpload",
  "interfaceName": "FileUploadProps",
  "description": "Props for the FileUpload component.",
  "sourcePath": "src\\components\\FileUpload\\FileUpload.types.ts",
  "props": [
    {
      "name": "allowedFileTypes",
      "type": "string[]",
      "description": "Allowed file MIME types or file extensions (e.g. \".pdf\", \"image/png\").",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "controlRounding",
      "type": "RoundingType",
      "description": "Rounding of the control button ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "controlShadow",
      "type": "ShadowType",
      "description": "Shadow of the control button ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "description",
      "type": "string",
      "description": "Optional description text under the label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "descriptionClassName",
      "type": "string",
      "description": "Additional class names for the FormGroup description.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether to disable the file input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "dropzoneClassName",
      "type": "string",
      "description": "Additional class names for the dropzone/root wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "dropzoneDescription",
      "type": "string",
      "description": "Optional custom instructions for drag-and-drop users and assistive tech.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "dropzoneRole",
      "type": "\"button\" | \"group\" | \"region\"",
      "description": "Whether the dropzone should expose a button-like role.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"group\""
    },
    {
      "name": "enableDragAndDrop",
      "type": "boolean",
      "description": "Whether drag and drop is enabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "error",
      "type": "string",
      "description": "Optional error message.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorMessageClassName",
      "type": "string",
      "description": "Additional class names for the FormGroup error message.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "failureMessage",
      "type": "string",
      "description": "Status message announced when upload fails.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Upload failed. Please try again.\""
    },
    {
      "name": "fileListAriaLabel",
      "type": "string",
      "description": "Accessible label for the selected files list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fileListClassName",
      "type": "string",
      "description": "Additional class names for the selected files list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fileListItemClassName",
      "type": "string",
      "description": "Additional class names for each selected file item.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fileRemovedMessage",
      "type": "((fileName: string, index: number) => string)",
      "description": "Message announced when a file is removed.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "filesSelectedMessage",
      "type": "((files: File[]) => string)",
      "description": "Message announced when files are selected.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "formGroupClassName",
      "type": "string",
      "description": "Additional class names for the outer FormGroup wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Adds glass styling to the dropzone and nested controls.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional custom id for the root/input relationship.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputAriaLabel",
      "type": "string",
      "description": "Accessible label for the hidden native file input when no visible label is used.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputClassName",
      "type": "string",
      "description": "Additional class names for the visually hidden native input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Label displayed above the file input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Upload File\""
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class names for the FormGroup label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "liveRegionPoliteness",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Live region politeness for status updates.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"polite\""
    },
    {
      "name": "maxFileSizeBytes",
      "type": "number",
      "description": "Maximum file size in bytes (e.g., 5MB = 5 * 1024 * 1024).",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "Infinity"
    },
    {
      "name": "multiple",
      "type": "boolean",
      "description": "Allows multiple file selection if true.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "onFilesChange",
      "type": "((files: File[]) => void)",
      "description": "Called whenever selected files change.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onSubmit",
      "type": "(files: File[]) => void | Promise<void>",
      "description": "Called after upload completes.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to display the control button as an outline.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "outlineRounding",
      "type": "RoundingType",
      "description": "Rounding of the wrapping element ('none' | 'small' | 'medium' | 'large' | 'full').",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "outlineShadow",
      "type": "ShadowType",
      "description": "Shadow of the wrapping element ('none' | 'light' | 'medium' | 'strong' | 'intense').",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "rejectedFilesAriaLabel",
      "type": "string",
      "description": "Accessible label for the rejected files list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rejectedFilesClassName",
      "type": "string",
      "description": "Additional class names for the rejected files wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rejectedFilesMessage",
      "type": "((files: { name: string; reason: string; }[]) => string)",
      "description": "Message announced when rejected files are detected.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "rejectedItemClassName",
      "type": "string",
      "description": "Additional class names for each rejected file item.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rejectedLabelClassName",
      "type": "string",
      "description": "Additional class names for the rejected files label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rejectedListClassName",
      "type": "string",
      "description": "Additional class names for the rejected files list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rejectedReasonClassName",
      "type": "string",
      "description": "Additional class names for each rejected reason.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "removeButtonClassName",
      "type": "string",
      "description": "Additional class names for each remove-file button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "removeFileAriaLabel",
      "type": "((fileName: string, index: number) => string)",
      "description": "Accessible label template for remove buttons.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the file input is required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "selectButtonAriaLabel",
      "type": "string",
      "description": "Accessible label for the upload trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "selectButtonClassName",
      "type": "string",
      "description": "Additional class names for the select-file button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "The state of the file upload ('success' | 'error' | 'warning' | 'disabled' | '').",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "successMessage",
      "type": "string",
      "description": "Status message announced when upload succeeds.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Upload successful.\""
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"file-upload\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for the buttons and progress bar ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "uploadActionsClassName",
      "type": "string",
      "description": "Additional class names for the upload actions wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "uploadButtonAriaLabel",
      "type": "string",
      "description": "Accessible label for the submit/upload button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "uploadButtonClassName",
      "type": "string",
      "description": "Additional class names for the upload button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "uploadControlsClassName",
      "type": "string",
      "description": "Additional class names for the upload controls wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "uploadProgress",
      "type": "number",
      "description": "External upload progress value (overrides internal simulation).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "uploadProgressClassName",
      "type": "string",
      "description": "Additional class names for the upload progress bar.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
