/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const formGroupPropDocs: GeneratedComponentDoc = {
  "name": "FormGroup",
  "interfaceName": "FormGroupProps",
  "description": "Props for the FormGroup component.",
  "sourcePath": "src/components/FormGroup/FormGroup.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional override for the wrapper aria-describedby.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Optional aria-label for the wrapper group.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional override for the wrapper aria-labelledby.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "children",
      "type": "ReactElement<unknown, string | JSXElementConstructor<any>> | ReactElement<unknown, string | JSXElementConstructor<...>>[]",
      "description": "The form element or component (input, textarea, etc.).",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class names for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "controller",
      "type": "ReactNode",
      "description": "Optional controller element (e.g., button, icon) beside input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "controllerClassName",
      "type": "string",
      "description": "Additional class names for the optional controller wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "descriptionClassName",
      "type": "string",
      "description": "Additional class names for the helper description.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorMessage",
      "type": "string",
      "description": "Optional error message shown below the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorMessageClassName",
      "type": "string",
      "description": "Additional class names for the error message.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperText",
      "type": "string",
      "description": "Optional helper text displayed below the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "hideLabel",
      "type": "boolean",
      "description": "If true, visually hides the label but keeps it accessible.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Unique ID for the input and label association.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputFieldClassName",
      "type": "string",
      "description": "Additional class names for each input field wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputWrapperClassName",
      "type": "string",
      "description": "Additional class names for each input wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Label for the input field.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class names for the label element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "layout",
      "type": "\"horizontal\" | \"vertical\"",
      "description": "Layout style for label and input. \"vertical\" (default) or \"horizontal\"",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"vertical\""
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the field is required (adds asterisk).",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "requiredClassName",
      "type": "string",
      "description": "Additional class names for the required marker.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "role",
      "type": "AriaRole",
      "description": "Optional role for the wrapper. Defaults to \"group\".",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"group\""
    },
    {
      "name": "spacing",
      "type": "SizeType",
      "description": "Spacing size between each input in the form group. ('xs' | 'small' | 'medium' | 'large' | 'xl')",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"xs\""
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"form-group\""
    }
  ]
};
