/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const formFieldPropDocs: GeneratedComponentDoc = {
  "name": "FormField",
  "interfaceName": "FormFieldProps",
  "description": "",
  "sourcePath": "src\\components\\FormField\\FormField.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactElement<Record<string, unknown>, string | JSXElementConstructor<any>>",
      "description": "Content rendered inside the component.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "controlClassName",
      "type": "string",
      "description": "Additional CSS class names for the control section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "error",
      "type": "ReactNode",
      "description": "Error message or error state displayed with the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorClassName",
      "type": "string",
      "description": "Additional CSS class names for the error section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "Helper text displayed with the field.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperTextClassName",
      "type": "string",
      "description": "Additional CSS class names for the helper text section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "id",
      "type": "string",
      "description": "HTML id applied to the relevant element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible label content for the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional CSS class names for the label section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Label Position.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "optionalText",
      "type": "ReactNode",
      "description": "Optional Text.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Optional\""
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
