/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const inputGroupPropDocs: GeneratedComponentDoc = {
  "name": "InputGroup",
  "interfaceName": "InputGroupProps",
  "description": "Props for the InputGroup component.",
  "sourcePath": "src\\components\\InputGroup\\InputGroup.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Main form control rendered inside the group.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class name for the outer label/component container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class name for the content/control area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "description",
      "type": "ReactNode",
      "description": "Supporting description rendered before the control and connected with aria-describedby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "descriptionClassName",
      "type": "string",
      "description": "Additional class name for the description text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the grouped control is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "endAddon",
      "type": "ReactNode",
      "description": "Addon content rendered after the shared input frame.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "endAddonClassName",
      "type": "string",
      "description": "Additional class name for the end addon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "error",
      "type": "ReactNode",
      "description": "Error message rendered after the control and announced to assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorClassName",
      "type": "string",
      "description": "Additional class name for error text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "frameClassName",
      "type": "string",
      "description": "Additional class name for the input frame.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "description": "Whether the group should stretch to the full available width.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Whether to render glass styling.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "Helper text rendered after the control and connected with aria-describedby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperTextClassName",
      "type": "string",
      "description": "Additional class name for helper text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Optional visible label for the grouped control.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the component.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "loadingMessage",
      "type": "ReactNode",
      "description": "Accessible loading message rendered while loading is true.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Loading\""
    },
    {
      "name": "optionalText",
      "type": "ReactNode",
      "description": "Optional text rendered beside the label when required is false.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Optional\""
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to render outlined styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "prefix",
      "type": "ReactNode",
      "description": "Content rendered before the control inside the shared input frame.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "prefixClassName",
      "type": "string",
      "description": "Additional class name for prefix content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the grouped control is required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "startAddon",
      "type": "ReactNode",
      "description": "Addon content rendered before the shared input frame.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "startAddonClassName",
      "type": "string",
      "description": "Additional class name for the start addon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "suffix",
      "type": "ReactNode",
      "description": "Content rendered after the control inside the shared input frame.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "suffixClassName",
      "type": "string",
      "description": "Additional class name for suffix content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"input-group\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    }
  ]
};
