/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const legendPropDocs: GeneratedComponentDoc = {
  name: "Legend",
  interfaceName: "LegendProps",
  description: "Props for the Legend component.",
  sourcePath: "src\\components\\Legend\\Legend.types.ts",
  props: [
    {
      name: "className",
      type: "string",
      description: "Additional class name for the root.",
      required: false,
      inherited: false,
      category: "styling",
    },
    {
      name: "data-testid",
      type: "string",
      description: "Backward-compatible alias for test ID attributes.",
      required: false,
      inherited: false,
      category: "testing",
    },
    {
      name: "items",
      type: "LegendItem[]",
      description: "Items rendered in the legend.",
      required: true,
      inherited: false,
      category: "props",
    },
    {
      name: "label",
      type: "ReactNode",
      description: "Visible legend label.",
      required: false,
      inherited: false,
      category: "props",
    },
    {
      name: "loading",
      type: "boolean",
      description: "Whether the component should display a loading state.",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: "false",
    },
    {
      name: "orientation",
      type: '"horizontal" | "vertical"',
      description: "Legend orientation.",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: '"horizontal"',
    },
    {
      name: "state",
      type: "StateType",
      description: "Visual state class used for styling.",
      required: false,
      inherited: false,
      category: "styling",
    },
    {
      name: "testId",
      type: "string",
      description: "Optional test ID for testing frameworks.",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: 'dataTestId ?? "legend"',
    },
    {
      name: "theme",
      type: "ThemeType",
      description: "Theme class used for styling.",
      required: false,
      inherited: false,
      category: "styling",
      defaultValue: '"primary"',
    },
  ],
};
