/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const lineChartPropDocs: GeneratedComponentDoc = {
  "name": "LineChart",
  "interfaceName": "LineChartProps",
  "description": "Props for the LineChart component.",
  "sourcePath": "src\\components\\LineChart\\LineChart.types.ts",
  "props": [
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the chart graphic.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "color",
      "type": "string",
      "description": "Stroke color for the line.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"currentColor\""
    },
    {
      "name": "data",
      "type": "ChartDatum[]",
      "description": "Labelled values rendered as a line chart.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "height",
      "type": "number",
      "description": "Height of the SVG viewport.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "200"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible chart label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "padding",
      "type": "number",
      "description": "Inner SVG padding.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "24"
    },
    {
      "name": "showGrid",
      "type": "boolean",
      "description": "Whether to render guide lines.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "showPoints",
      "type": "boolean",
      "description": "Whether to render point markers.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"line-chart\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"primary\""
    },
    {
      "name": "valueFormatter",
      "type": "ChartValueFormatter",
      "description": "Formatter used for visible and accessible values.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "formatDefaultValue"
    },
    {
      "name": "width",
      "type": "number",
      "description": "Width of the SVG viewport.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "360"
    }
  ]
};
