/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const menuPropDocs: GeneratedComponentDoc = {
  "name": "Menu",
  "interfaceName": "MenuProps",
  "description": "Props for the Menu component.",
  "sourcePath": "src\\components\\Menu\\Menu.types.ts",
  "props": [
    {
      "name": "activation",
      "type": "MenuActivation",
      "description": "How the menu opens. Defaults to \"click\" when `trigger` is provided, otherwise \"contextmenu\".",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "trigger ? \"click\" : \"contextmenu\""
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Accessible description id(s) for the menu panel.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the menu panel.",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"Context menu\""
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Accessible labelledby target for the menu panel.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Context target content. Used when opening by click or context menu.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for the outer wrapper.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "closeOnSelect",
      "type": "boolean",
      "description": "Whether the menu closes after selecting a non-submenu item.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultOpen",
      "type": "boolean",
      "description": "Initial open state for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "focusFirstItemOnOpen",
      "type": "boolean",
      "description": "Whether focus moves to the first enabled item when the menu opens.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Adds glass styling to the menu panel.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional id for the outer wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "itemClassName",
      "type": "string",
      "description": "Optional class name merged onto every actionable menu item.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "items",
      "type": "MenuItem[]",
      "description": "Array of menu items, labels, separators, and submenu triggers to render.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuClassName",
      "type": "string",
      "description": "Optional class name for the root menu panel.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "menuId",
      "type": "string",
      "description": "Optional id for the root menu panel.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onKeyDown",
      "type": "((event: KeyboardEvent<HTMLDivElement>) => void)",
      "description": "Keydown handler for the outer wrapper, called before internal handling.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onOpenChange",
      "type": "((open: boolean) => void)",
      "description": "Called whenever the open state changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onPositionChange",
      "type": "((position: MenuPosition) => void)",
      "description": "Called whenever the menu position changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "open",
      "type": "boolean",
      "description": "Controlled open state.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "position",
      "type": "MenuPosition",
      "description": "Controlled menu position in viewport coordinates.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the menu panel.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the menu panel.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State styling for the menu.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "targetClassName",
      "type": "string",
      "description": "Optional class name for the context target wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"menu\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for styling ('primary' | 'secondary' | 'tertiary' | 'quaternary' | 'clear').",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "trigger",
      "type": "ReactNode",
      "description": "Optional explicit trigger content rendered as a button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerClassName",
      "type": "string",
      "description": "Optional class name for the trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
