/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const messagePopupPropDocs: GeneratedComponentDoc = {
  "name": "MessagePopup",
  "interfaceName": "MessagePopupProps",
  "description": "Props for the MessagePopup component.",
  "sourcePath": "src/components/MessagePopup/MessagePopup.types.ts",
  "props": [
    {
      "name": "actionsClassName",
      "type": "string",
      "description": "Additional class name applied to the actions element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID of an element that describes the dialog.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the dialog.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label-close-button",
      "type": "string",
      "description": "Accessible label for the close button.",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"Close\""
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID of an element that labels the dialog.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "aria-live value applied to the message element.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "bodyClassName",
      "type": "string",
      "description": "Additional class name applied to the body element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "cancelButtonClassName",
      "type": "string",
      "description": "Additional class name applied to the cancel button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "cancelText",
      "type": "string",
      "description": "Text for the cancel button.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Cancel\""
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name applied to the wrapper element.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "closeButtonClassName",
      "type": "string",
      "description": "Additional class name applied to the close button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "confirmButtonClassName",
      "type": "string",
      "description": "Additional class name applied to the confirm button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "confirmText",
      "type": "string",
      "description": "Text for the confirm button.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Confirm\""
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class name applied to the dialog content element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for testId.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "dialogRole",
      "type": "\"alertdialog\" | \"dialog\"",
      "description": "The ARIA role for the dialog element.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"dialog\""
    },
    {
      "name": "headerClassName",
      "type": "string",
      "description": "Additional class name applied to the header element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "message",
      "type": "string",
      "description": "The message to display inside the popup.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "messageClassName",
      "type": "string",
      "description": "Additional class name applied to the message element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onCancel",
      "type": "(() => void)",
      "description": "Callback fired when the cancel button is clicked.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onClose",
      "type": "() => void",
      "description": "Callback fired when the popup is closed.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onConfirm",
      "type": "(() => void)",
      "description": "Callback fired when the confirm button is clicked.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the popup corners.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the popup.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test ID for the root element.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"message-popup\""
    },
    {
      "name": "title",
      "type": "string",
      "description": "Optional title shown in the popup header.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleClassName",
      "type": "string",
      "description": "Additional class name applied to the title element.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
