/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const metricBoxPropDocs: GeneratedComponentDoc = {
  "name": "MetricBox",
  "interfaceName": "MetricBoxProps",
  "description": "Props for the MetricBox component.",
  "sourcePath": "src\\components\\MetricBox\\MetricBox.types.ts",
  "props": [
    {
      "name": "align",
      "type": "\"left\" | \"right\" | \"center\"",
      "description": "Text alignment for content. One of: \"left\" | \"center\" | \"right\"",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"center\""
    },
    {
      "name": "aria-atomic",
      "type": "boolean",
      "description": "Whether assistive tech should present the live region as a whole.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Custom accessible description reference for the whole metric box. Overrides the internal subtext description when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Custom accessible label for the whole metric box. Use when the title/value pairing needs a more descriptive spoken label.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Custom accessible label reference for the whole metric box. Overrides the internal title-based labelling when provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-live",
      "type": "\"off\" | \"polite\" | \"assertive\"",
      "description": "Live region setting for announcing metric value updates. Useful for dynamic dashboards.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional additional CSS class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class names for the content wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "decorativeIcon",
      "type": "boolean",
      "description": "Whether the icon is decorative. Defaults to true.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Applies a translucent frosted-glass treatment using the active theme palette.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "icon",
      "type": "IconType",
      "description": "Optional icon to visually represent the metric (from react-icons, for example).",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconAriaLabel",
      "type": "string",
      "description": "Accessible label for the icon when it is not decorative.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Additional class names for the icon wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Optional outline style for the component (default: false).",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Accessible role for the wrapper. Defaults to \"region\" when a title is present.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the component. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size of the component. One of: \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the metric. One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "subtext",
      "type": "string",
      "description": "Optional subtext providing additional context for the metric.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "subtextClassName",
      "type": "string",
      "description": "Additional class names for the subtext element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"metric-box\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme to apply for styling. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Title of the metric.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleClassName",
      "type": "string",
      "description": "Additional class names for the title element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "value",
      "type": "string | number",
      "description": "The primary value of the metric, e.g., a number or a string.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "valueClassName",
      "type": "string",
      "description": "Additional class names for the value element.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
