/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const multiSelectPropDocs: GeneratedComponentDoc = {
  "name": "MultiSelect",
  "interfaceName": "MultiSelectProps",
  "description": "Props for the MultiSelect component.",
  "sourcePath": "src/components/MultiSelect/MultiSelect.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References one or more elements that describe the trigger.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "description": "Marks the field as invalid for assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Explicit accessible label for the trigger when no visible label is provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References one or more elements that label the trigger.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "description": "Indicates the field is required to assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "chipClassName",
      "type": "string",
      "description": "Additional class name for each selected-value chip.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "clearAriaLabel",
      "type": "string",
      "description": "Accessible label for the clear-all button.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Clear selected options\""
    },
    {
      "name": "clearable",
      "type": "boolean",
      "description": "Whether to show a clear-all button when values are selected.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class name for the outer label/component container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultValue",
      "type": "string[]",
      "description": "Initially selected option values for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the component is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "emptyMessage",
      "type": "ReactNode",
      "description": "Message shown when filtering leaves no visible options.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"No options found\""
    },
    {
      "name": "errorMessage",
      "type": "ReactNode",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Optional visible label for the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the component.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "listboxClassName",
      "type": "string",
      "description": "Additional class name for the option listbox.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "loadingMessage",
      "type": "ReactNode",
      "description": "Message announced while the component is loading.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Loading options\""
    },
    {
      "name": "maxSelected",
      "type": "number",
      "description": "Maximum number of selected options allowed.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "name",
      "type": "string",
      "description": "HTML name used for hidden inputs when participating in form submission.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((values: string[], options: MultiSelectOption[]) => void)",
      "description": "Callback fired whenever selected values change.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "optionClassName",
      "type": "string",
      "description": "Additional class name for each option row.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "options",
      "type": "MultiSelectOption[]",
      "description": "Options available for selection.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Placeholder displayed when no options are selected.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Select options\""
    },
    {
      "name": "popoverClassName",
      "type": "string",
      "description": "Additional class name for the popup panel.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the field is required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "searchInputClassName",
      "type": "string",
      "description": "Additional class name for the filter input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "searchPlaceholder",
      "type": "string",
      "description": "Text shown in the filter input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Filter options\""
    },
    {
      "name": "searchable",
      "type": "boolean",
      "description": "Whether users can filter options by typing.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"multi-select\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "toggleAriaLabel",
      "type": "string",
      "description": "Accessible label for the popup toggle.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "triggerClassName",
      "type": "string",
      "description": "Additional class name for the trigger button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "value",
      "type": "string[]",
      "description": "Currently selected option values for controlled usage.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "valueListClassName",
      "type": "string",
      "description": "Additional class name for the selected-value chip row.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
