/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const navBarPropDocs: GeneratedComponentDoc = {
  "name": "NavBar",
  "interfaceName": "NavBarProps",
  "description": "Props for the reusable NavBar component.",
  "sourcePath": "src\\components\\NavBar\\NavBar.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional ID of an element that describes this navigation landmark.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the navigation landmark. Defaults to \"Main navigation\".",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"Main navigation\""
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional ID of an external element that labels this navigation landmark. Prefer this when the nav is visually labelled by a heading.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional extra class name(s) for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"\""
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "getItemAriaLabel",
      "type": "((item: NavItem) => string)",
      "description": "Optional callback to provide a custom accessible label for each nav item. Falls back to the item label when not provided.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Adds translucent glass styling to nav items.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "isItemActive",
      "type": "((item: NavItem) => boolean)",
      "description": "Optional callback used to determine whether a nav item should be styled as active.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "items",
      "type": "NavItem[]",
      "description": "Array of navigation items to render in the NavBar.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "list-aria-label",
      "type": "string",
      "description": "Optional accessible label for the internal navigation list. Usually not required, but useful in complex layouts.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Main navigation items\""
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Optional rounding to apply to the NavBar. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Optional shadow to apply to the NavBar. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"nav-bar\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Optional theme class names to apply to the NavBar. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    }
  ]
};
