/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const numberInputPropDocs: GeneratedComponentDoc = {
  "name": "NumberInput",
  "interfaceName": "NumberInputProps",
  "description": "Props for the NumberInput component.",
  "sourcePath": "src\\components\\NumberInput\\NumberInput.types.ts",
  "props": [
    {
      "name": "clampOnBlur",
      "type": "boolean",
      "description": "Whether to clamp values to min/max on blur and when using stepper buttons.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class name for the outer label/input container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "controlsClassName",
      "type": "string",
      "description": "Additional class name for the stepper controls wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "decrementAriaLabel",
      "type": "string",
      "description": "Accessible label for the decrement control.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Decrease value\""
    },
    {
      "name": "decrementButtonClassName",
      "type": "string",
      "description": "Additional class name for the decrement button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "defaultValue",
      "type": "number | \"\"",
      "description": "Initial numeric value for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"\""
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Whether to render glass styling.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "incrementAriaLabel",
      "type": "string",
      "description": "Accessible label for the increment control.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Increase value\""
    },
    {
      "name": "incrementButtonClassName",
      "type": "string",
      "description": "Additional class name for the increment button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputClassName",
      "type": "string",
      "description": "Additional class name for the native input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible label content for the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the input.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "max",
      "type": "number",
      "description": "Maximum allowed value.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "min",
      "type": "number",
      "description": "Minimum allowed value.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((value: number | \"\", event: React.ChangeEvent<HTMLInputElement>) => void)",
      "description": "Callback fired when the numeric value changes. The first argument is `\"\"` when the input is empty.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onValueChange",
      "type": "((value: number) => void)",
      "description": "Callback fired with numeric values only. Empty or invalid values are ignored.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to render outlined styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Placeholder shown when the input is empty and no label is floating.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Enter number\""
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the input.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the input.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "showControls",
      "type": "boolean",
      "description": "Whether to show increment/decrement stepper buttons.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "step",
      "type": "number",
      "description": "Increment/decrement step.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "1"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"number-input\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "value",
      "type": "number | \"\"",
      "description": "Current numeric value for controlled usage.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
