/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const pageHeaderPropDocs: GeneratedComponentDoc = {
  "name": "PageHeader",
  "interfaceName": "PageHeaderProps",
  "description": "Props for the PageHeader component.",
  "sourcePath": "src\\components\\PageHeader\\PageHeader.types.ts",
  "props": [
    {
      "name": "actions",
      "type": "ReactNode",
      "description": "Primary action area rendered at the end of the header.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "actionsClassName",
      "type": "string",
      "description": "Additional class name for the actions area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "as",
      "type": "\"div\" | \"header\" | \"section\"",
      "description": "Semantic element used for the root.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"header\""
    },
    {
      "name": "before",
      "type": "ReactNode",
      "description": "Optional content rendered before the title block.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Additional header content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "compact",
      "type": "boolean",
      "description": "Whether title/actions should stack more tightly.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class name for the content area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the header is visually disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "eyebrow",
      "type": "ReactNode",
      "description": "Small text rendered above the title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footer",
      "type": "ReactNode",
      "description": "Optional content rendered after the main row.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "description": "Whether the header should stretch to full width.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Whether to render glass styling.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "icon",
      "type": "ReactNode",
      "description": "Optional leading visual or icon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Legacy alias for title retained for scaffold compatibility.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the header should display a loading indicator.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "meta",
      "type": "ReactNode",
      "description": "Supplemental metadata rendered near the title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to render outlined styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default outline setting (fallback: false)"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "subtitle",
      "type": "ReactNode",
      "description": "Supporting subtitle or description.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "subtitleClassName",
      "type": "string",
      "description": "Additional class name for the subtitle.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"page-header\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "description": "Main page title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleClassName",
      "type": "string",
      "description": "Additional class name for the title.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
