/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const portalPropDocs: GeneratedComponentDoc = {
  "name": "Portal",
  "interfaceName": "PortalProps",
  "description": "Props for the Portal component.",
  "sourcePath": "src\\components\\Portal\\Portal.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Content rendered into the target container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for the portal wrapper.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "container",
      "type": "string | Element | DocumentFragment | null",
      "description": "Element, selector, or null target for the portal.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Legacy class name for the outer container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Legacy class name for the content area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the portal should render in place instead of using createPortal.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Whether to render glass styling.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Legacy visible label retained for scaffold compatibility.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Legacy class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Legacy label position retained for scaffold compatibility.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "outline",
      "type": "boolean",
      "description": "Whether to render outlined styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "renderInlineUntilMounted",
      "type": "boolean",
      "description": "Whether children should render before the target is available.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"portal\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    }
  ]
};
