/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const portalPropDocs: GeneratedComponentDoc = {
  "name": "Portal",
  "interfaceName": "PortalProps",
  "description": "Props for the Portal component.",
  "sourcePath": "src/components/Portal/Portal.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Content rendered into the target container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional class name for the portal wrapper.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "container",
      "type": "string | Element | DocumentFragment | null",
      "description": "Element, selector, or null target for the portal.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the portal should render in place instead of using createPortal.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "renderInlineUntilMounted",
      "type": "boolean",
      "description": "Whether children should render before the target is available.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"portal\""
    }
  ]
};
