/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const radioGroupPropDocs: GeneratedComponentDoc = {
  "name": "RadioGroup",
  "interfaceName": "RadioGroupProps",
  "description": "",
  "sourcePath": "src/components/RadioButton/RadioButton.types.ts",
  "props": [
    {
      "name": "className",
      "type": "string",
      "description": "Custom class name for the root fieldset.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether every option in the group is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "errorMessage",
      "type": "ReactNode",
      "description": "Visible error message for invalid state.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "Marks the radio group as invalid.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "legend",
      "type": "ReactNode",
      "description": "Accessible group label displayed as a legend.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Name shared by all radio buttons in the group.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "(value: string) => void",
      "description": "Callback triggered with the selected option value.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "options",
      "type": "RadioButtonOption[]",
      "description": "Available radio options.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "optionsClassName",
      "type": "string",
      "description": "Custom class name for the options wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "orientation",
      "type": "\"horizontal\" | \"vertical\"",
      "description": "Layout direction for the radio options.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"vertical\""
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether selection is required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding of each radio control.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style of each radio control.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the radio group.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"radio-group\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme applied for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Currently selected option value.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
