/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const ratingPropDocs: GeneratedComponentDoc = {
  name: "Rating",
  interfaceName: "RatingProps",
  description: "Props for the Rating component.",
  sourcePath: "src\\components\\Rating\\Rating.types.ts",
  props: [
    {
      name: "aria-describedby",
      type: "string",
      description:
        "References the id of an element that describes the rating group.",
      required: false,
      inherited: false,
      category: "aria",
    },
    {
      name: "aria-label",
      type: "string",
      description:
        "Accessible label for the rating group. Prefer `label` when a visible label is needed.",
      required: false,
      inherited: false,
      category: "aria",
    },
    {
      name: "aria-labelledby",
      type: "string",
      description:
        "References the id of an element that labels the rating group.",
      required: false,
      inherited: false,
      category: "aria",
    },
    {
      name: "className",
      type: "string",
      description: "Optional additional CSS class names for custom styling.",
      required: false,
      inherited: false,
      category: "styling",
    },
    {
      name: "data-testid",
      type: "string",
      description: "Backward-compatible alias for test ID attributes.",
      required: false,
      inherited: false,
      category: "testing",
    },
    {
      name: "id",
      type: "string",
      description: "Optional unique id for the rating group.",
      required: false,
      inherited: false,
      category: "props",
    },
    {
      name: "interactive",
      type: "boolean",
      description:
        "If true, the user can interact with the rating (hover, click, keyboard navigation).",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: "true",
    },
    {
      name: "label",
      type: "string",
      description: "Visible label for the rating component.",
      required: false,
      inherited: false,
      category: "props",
    },
    {
      name: "max",
      type: "number",
      description: "The maximum number of stars available for the rating.",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: "5",
    },
    {
      name: "onChange",
      type: "((rating: number) => void)",
      description:
        "Callback function invoked when the rating changes. Receives the new rating (1-indexed) as its argument.",
      required: false,
      inherited: false,
      category: "events",
    },
    {
      name: "readOnly",
      type: "boolean",
      description: "If true, the rating is read-only and cannot be changed.",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: "false",
    },
    {
      name: "required",
      type: "boolean",
      description: "If true, marks the field as required.",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: "false",
    },
    {
      name: "size",
      type: "SizeType",
      description:
        'The size of the rating component. One of: "xs" | "small" | "medium" | "large" | "xl"',
      required: false,
      inherited: false,
      category: "styling",
      defaultValue: 'configured default size (fallback: "medium")',
    },
    {
      name: "starAriaLabelPrefix",
      type: "string",
      description:
        'Optional aria-label prefix for each star. Example: "Rating star" -> "Rating star 1 of 5"',
      required: false,
      inherited: false,
      category: "props",
      defaultValue: '"Rate"',
    },
    {
      name: "state",
      type: "StateType",
      description:
        'State of the rating. One of: "success" | "error" | "warning" | "disabled" | ""',
      required: false,
      inherited: false,
      category: "styling",
    },
    {
      name: "testId",
      type: "string",
      description: "Optional test ID for testing frameworks.",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: 'dataTestId ?? "rating"',
    },
    {
      name: "theme",
      type: "ThemeType",
      description:
        'The theme to use for styling. One of: "primary" | "secondary" | "tertiary" | "quaternary" | "clear"',
      required: false,
      inherited: false,
      category: "styling",
      defaultValue: 'configured default theme (fallback: "primary")',
    },
    {
      name: "value",
      type: "number",
      description: "The current rating value.",
      required: true,
      inherited: false,
      category: "props",
    },
    {
      name: "variant",
      type: 'import("C:/Users/davin/Documents/Web Design/boreal-ui/src/index.core").VariantType',
      description:
        "Surface treatment; glassOutline combines glass and outline.",
      required: false,
      inherited: false,
      category: "props",
      defaultValue: "getDefaultVariant()",
    },
  ],
};
