/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const searchInputPropDocs: GeneratedComponentDoc = {
  "name": "SearchInput",
  "interfaceName": "SearchInputProps",
  "description": "Props for the SearchInput component.",
  "sourcePath": "src/components/SearchInput/SearchInput.types.ts",
  "props": [
    {
      "name": "autoComplete",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "clearAriaLabel",
      "type": "string",
      "description": "Accessible label for the clear button.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Clear search\""
    },
    {
      "name": "clearButtonClassName",
      "type": "string",
      "description": "Additional class name for the clear button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class name for the outer label/input container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultValue",
      "type": "string",
      "description": "Initial search query for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"\""
    },
    {
      "name": "errorMessage",
      "type": "ReactNode",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "icon",
      "type": "SearchInputIconComponent | null",
      "description": "Optional icon component to render inside the search input. Pass null to hide the default search icon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Additional class name for the rendered icon.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconPosition",
      "type": "\"left\" | \"right\"",
      "description": "Position of the icon relative to the input text.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"left\""
    },
    {
      "name": "iconWrapperClassName",
      "type": "string",
      "description": "Additional class name for the icon wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputClassName",
      "type": "string",
      "description": "Additional class name for the native search input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible label content for the search field.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the search field.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether to show the field as loading or waiting for search results.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "onChange",
      "type": "((value: string, event: React.ChangeEvent<HTMLInputElement>) => void)",
      "description": "Callback fired whenever the search query changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onClear",
      "type": "((event: React.MouseEvent<HTMLButtonElement>) => void)",
      "description": "Callback fired when the clear button is activated.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onSearch",
      "type": "((value: string, event: React.KeyboardEvent<HTMLInputElement> | React.MouseEvent<HTMLButtonElement>) => void)",
      "description": "Callback fired when the user submits a search by pressing Enter or activating the optional search button.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Placeholder shown when the search field is empty and no visible label is present.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Search\""
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding style for the search input.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "searchAriaLabel",
      "type": "string",
      "description": "Accessible label for the optional search button.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Search\""
    },
    {
      "name": "searchButtonClassName",
      "type": "string",
      "description": "Additional class name for the optional search button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the search input.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "showClearButton",
      "type": "boolean",
      "description": "Whether to show a clear button when the search query has a value.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "showSearchButton",
      "type": "boolean",
      "description": "Whether to show a dedicated search submit button.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"search-input\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Current search query for controlled usage.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
