/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const segmentedControlPropDocs: GeneratedComponentDoc = {
  "name": "SegmentedControl",
  "interfaceName": "SegmentedControlProps",
  "description": "Props for the SegmentedControl component.",
  "sourcePath": "src/components/SegmentedControl/SegmentedControl.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Main content rendered inside the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class name for the outer label/component container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class name for the content area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultValue",
      "type": "string",
      "description": "Initial selected value for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the component is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "equalWidth",
      "type": "boolean",
      "description": "Whether options should share available width evenly.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "description": "Whether the control should stretch to the full available width.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Optional visible label for the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the component.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "loopNavigation",
      "type": "boolean",
      "description": "Whether arrow-key navigation wraps from last to first option.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Name submitted by the hidden form input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onValueChange",
      "type": "((value: string, option: SegmentedControlOption) => void)",
      "description": "Callback fired when a segment is selected.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "optionClassName",
      "type": "string",
      "description": "Additional class name applied to every option.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "optionIconClassName",
      "type": "string",
      "description": "Additional class name for option icons.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "optionLabelClassName",
      "type": "string",
      "description": "Additional class name for option labels.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "options",
      "type": "SegmentedControlOption[]",
      "description": "Options rendered as selectable segments.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "orientation",
      "type": "\"horizontal\" | \"vertical\"",
      "description": "Layout direction for the segment list.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"horizontal\""
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "Whether the hidden form input should be required.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "selectedOptionClassName",
      "type": "string",
      "description": "Additional class name for selected options.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"segmented-control\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "value",
      "type": "string",
      "description": "Controlled selected value.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
