/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const sidebarPropDocs: GeneratedComponentDoc = {
  "name": "Sidebar",
  "interfaceName": "SidebarProps",
  "description": "",
  "sourcePath": "src/components/Sidebar/Sidebar.types.ts",
  "props": [
    {
      "name": "activeClassName",
      "type": "string",
      "description": "Additional class name applied when a link/item is active.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "ID reference to one or more elements that describe the sidebar navigation landmark.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the navigation landmark. Prefer the kebab-case ARIA prop for consistency with other React ARIA props.",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"Sidebar navigation\""
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "ID reference to one or more elements that label the sidebar navigation landmark. Takes precedence over aria-label when both are provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "chevronClassName",
      "type": "string",
      "description": "Additional class name for chevron icons.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "chevronOpenClassName",
      "type": "string",
      "description": "Additional class name applied when the chevron is open.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "childLinkClassName",
      "type": "string",
      "description": "Additional class name for child link-style items.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "childListClassName",
      "type": "string",
      "description": "Additional class name for nested child lists.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name(s) for applying custom styles.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "expandButtonClassName",
      "type": "string",
      "description": "Additional class name for expandable parent buttons.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "expandLabelClassName",
      "type": "string",
      "description": "Additional class name for expandable item labels.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerAriaLabel",
      "type": "string",
      "description": "Optional label for the footer landmark when footer content is rendered. Example: \"Sidebar footer links\"",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Sidebar footer\""
    },
    {
      "name": "footerAriaLabelledBy",
      "type": "string",
      "description": "Optional ID reference to label the footer landmark.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerClassName",
      "type": "string",
      "description": "Additional class name for the footer wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerLinkClassName",
      "type": "string",
      "description": "Additional class name for footer links.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerLinks",
      "type": "SidebarFooterLink[]",
      "description": "Array of footer links to render when `showFooter` is `true`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerVersion",
      "type": "string",
      "description": "Optional version string displayed in the sidebar footer. Example: \"v1.2.3\"",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "footerVersionClassName",
      "type": "string",
      "description": "Additional class name for the footer version text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "getExpandButtonAriaDescription",
      "type": "((link: SidebarLink, isOpen: boolean) => string)",
      "description": "Optional accessible description generator for expandable parent items.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "getExpandButtonAriaLabel",
      "type": "((link: SidebarLink, isOpen: boolean) => string)",
      "description": "Optional accessible label generator for expandable parent items. Useful when you want screen readers to hear something more descriptive than the visible text alone.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "hasActiveChild",
      "type": "((link: SidebarLink) => boolean)",
      "description": "Optional callback used to determine whether a link contains an active child.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Additional class name for item icons.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "isLinkActive",
      "type": "((link: SidebarLink) => boolean)",
      "description": "Optional callback used to determine whether a link should be styled as active.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "itemClassName",
      "type": "string",
      "description": "Additional class name for each list item.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "linkClassName",
      "type": "string",
      "description": "Additional class name for link-style items.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "links",
      "type": "SidebarLink[]",
      "description": "Array of navigation links to render in the sidebar. Each link may optionally include a nested submenu.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "listClassName",
      "type": "string",
      "description": "Additional class name for all sidebar lists.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "navClassName",
      "type": "string",
      "description": "Additional class name for the inner navigation wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding style for the sidebar container. - \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the sidebar container. - \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "showFooter",
      "type": "boolean",
      "description": "Whether to display a footer section at the bottom of the sidebar. Defaults to `false`.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State variant for styling. Typically used to apply semantic states to the component. - \"success\" | \"error\" | \"warning\" | \"info\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "submenuClassName",
      "type": "string",
      "description": "Additional class name for submenu containers.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "submenuOpenClassName",
      "type": "string",
      "description": "Additional class name applied when a submenu is open.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"sidebar\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme for styling. Determines the base color scheme for the sidebar. - \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
