/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const sliderPropDocs: GeneratedComponentDoc = {
  "name": "Slider",
  "interfaceName": "SliderProps",
  "description": "Props for the Slider component.",
  "sourcePath": "src\\components\\Slider\\Slider.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Id of external element(s) that describe the slider.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean | \"true\" | \"false\"",
      "description": "Marks the slider as invalid.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the slider if no visible label is provided.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Id of external element(s) that label the slider.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-orientation",
      "type": "\"horizontal\" | \"vertical\"",
      "description": "Orientation of the slider.",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"horizontal\""
    },
    {
      "name": "aria-required",
      "type": "boolean | \"true\" | \"false\"",
      "description": "Marks the slider as required for assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-valuemax",
      "type": "number",
      "description": "Explicit maximum value for assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-valuemin",
      "type": "number",
      "description": "Explicit minimum value for assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-valuenow",
      "type": "number",
      "description": "Explicit current numeric value for assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-valuetext",
      "type": "string",
      "description": "Human-friendly text alternative for the current value.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "If true, the slider is disabled and cannot be interacted with.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Applies a translucent frosted-glass treatment to the slider track.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "id",
      "type": "string",
      "description": "Optional id for the slider input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Optional label displayed above or beside the slider.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the slider.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "max",
      "type": "number",
      "description": "The maximum value of the slider.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "100"
    },
    {
      "name": "min",
      "type": "number",
      "description": "The minimum value of the slider.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "0"
    },
    {
      "name": "name",
      "type": "string",
      "description": "Optional form field name.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "(e: React.ChangeEvent<HTMLInputElement>) => void",
      "description": "Callback invoked when the slider value changes. Receives the change event from the input element.",
      "required": true,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onValueChange",
      "type": "((value: number) => void)",
      "description": "Callback invoked when the slider value changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "required",
      "type": "boolean",
      "description": "If true, the slider is required in form contexts.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Controls the rounding of the component. One of: \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Controls the shadow of the component. One of: \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "showValue",
      "type": "boolean",
      "description": "If true, the current slider value is displayed alongside the slider.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "Size variant for the slider. One of: \"xs\" | \"small\" | \"medium\" | \"large\" | \"xl\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the slider. One of: \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "step",
      "type": "number",
      "description": "Increment step for the slider.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "1"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"slider\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme variant for styling. One of: \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "units",
      "type": "ReactNode",
      "description": "Unit text rendered after the displayed slider value.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "value",
      "type": "number",
      "description": "The current numeric value of the slider.",
      "required": true,
      "inherited": false,
      "category": "props"
    }
  ]
};
