/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const sparklinePropDocs: GeneratedComponentDoc = {
  "name": "Sparkline",
  "interfaceName": "SparklineProps",
  "description": "Props for the Sparkline component.",
  "sourcePath": "src/components/Sparkline/Sparkline.types.ts",
  "props": [
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the chart graphic.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "color",
      "type": "string",
      "description": "Stroke color for the line.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"currentColor\""
    },
    {
      "name": "data",
      "type": "ChartDatum[] | number[]",
      "description": "Numeric points or labelled values rendered as a compact line chart.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "height",
      "type": "number",
      "description": "Height of the SVG viewport.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "48"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible label rendered above the sparkline.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "padding",
      "type": "number",
      "description": "Inner SVG padding used when plotting points.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "4"
    },
    {
      "name": "showArea",
      "type": "boolean",
      "description": "Whether to fill the area below the line.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "showValue",
      "type": "boolean",
      "description": "Whether to render the last value next to the chart.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"sparkline\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"primary\""
    },
    {
      "name": "units",
      "type": "string",
      "description": "Optional unit label shown beside formatted values.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "valueFormatter",
      "type": "ChartValueFormatter",
      "description": "Formatter used for visible and accessible values.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "formatDefaultValue"
    },
    {
      "name": "width",
      "type": "number",
      "description": "Width of the SVG viewport.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "160"
    }
  ]
};
