/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const splitPanePropDocs: GeneratedComponentDoc = {
  "name": "SplitPane",
  "interfaceName": "SplitPaneProps",
  "description": "Props for the SplitPane component.",
  "sourcePath": "src/components/SplitPane/SplitPane.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Fallback children. When two children are supplied, they are used as start/end panes.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultSize",
      "type": "number",
      "description": "Initial size of the start pane as a percentage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "50"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the split pane is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "endPane",
      "type": "ReactNode",
      "description": "Content rendered in the second pane.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "endPaneClassName",
      "type": "string",
      "description": "Additional class name for the end pane.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the split pane should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "maxSize",
      "type": "number",
      "description": "Maximum start pane size as a percentage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "90"
    },
    {
      "name": "minSize",
      "type": "number",
      "description": "Minimum start pane size as a percentage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "10"
    },
    {
      "name": "onSizeChange",
      "type": "((size: number) => void)",
      "description": "Callback fired when the pane size changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "orientation",
      "type": "\"horizontal\" | \"vertical\"",
      "description": "Split orientation.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"horizontal\""
    },
    {
      "name": "resizable",
      "type": "boolean",
      "description": "Whether the divider can be resized.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "separatorAriaLabel",
      "type": "string",
      "description": "Accessible label for the resize separator.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Resize panes\""
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "number",
      "description": "Controlled size of the start pane as a percentage.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "startPane",
      "type": "ReactNode",
      "description": "Content rendered in the first pane.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "startPaneClassName",
      "type": "string",
      "description": "Additional class name for the start pane.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"split-pane\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
