/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const stackPropDocs: GeneratedComponentDoc = {
  "name": "Stack",
  "interfaceName": "StackProps",
  "description": "",
  "sourcePath": "src/components/Layout/Layout.types.ts",
  "props": [
    {
      "name": "align",
      "type": "LayoutAlign",
      "description": "Align prop for LayoutPrimitive.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "as",
      "type": "ElementType",
      "description": "As prop for LayoutPrimitive.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Content rendered inside the component.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for the component root.",
      "required": false,
      "inherited": true,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": true,
      "category": "testing"
    },
    {
      "name": "gap",
      "type": "LayoutGap",
      "description": "Gap.",
      "required": false,
      "inherited": true,
      "category": "props",
      "defaultValue": "\"md\""
    },
    {
      "name": "justify",
      "type": "LayoutJustify",
      "description": "Justify prop for LayoutPrimitive.",
      "required": false,
      "inherited": true,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": true,
      "category": "props"
    }
  ]
};
