/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const textAreaPropDocs: GeneratedComponentDoc = {
  "name": "TextArea",
  "interfaceName": "TextAreaProps",
  "description": "Props for the TextArea component.",
  "sourcePath": "src/components/TextArea/TextArea.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Legacy accessible description text rendered internally as visually hidden content. Prefer using `aria-describedby` when referencing external help text.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Legacy accessible label prop. Prefer using `aria-label`.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "autoComplete",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional custom CSS class name(s) to apply to the wrapper.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class names for the outer layout container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "describedBy",
      "type": "string",
      "description": "Optional id of external descriptive content. This will be merged with internally generated description ids.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "If true, the textarea is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "errorMessage",
      "type": "ReactNode",
      "description": "Optional error message shown below the textarea.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorMessageClassName",
      "type": "string",
      "description": "Additional class names for the error message.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "height",
      "type": "string | number",
      "description": "Optional height for the textarea.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "Optional helper text shown below the textarea.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperTextClassName",
      "type": "string",
      "description": "Additional class names for helper text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "icon",
      "type": "ComponentType<{ className?: string; \"aria-hidden\"?: boolean; }>",
      "description": "Optional icon to display alongside the textarea.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Additional class names for the icon wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputClassName",
      "type": "string",
      "description": "Additional class names for the textarea element.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Optional visible label for the textarea.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class names for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the textarea.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "onChange",
      "type": "((value: string, event: ChangeEvent<HTMLTextAreaElement>) => void)",
      "description": "Called when the textarea value changes. Receives the current string value and the original change event.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Placeholder text for the textarea.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Enter text\""
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "description": "If true, renders the textarea as read-only.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "resizable",
      "type": "boolean",
      "description": "If false, the textarea is not resizable.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "resizeHandleClassName",
      "type": "string",
      "description": "Additional class names for the resize handle.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class names for screen-reader-only description text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the text area.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"text-area\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
