/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const textInputPropDocs: GeneratedComponentDoc = {
  "name": "TextInput",
  "interfaceName": "TextInputProps",
  "description": "Props for the TextInput component.",
  "sourcePath": "src/components/TextInput/TextInput.types.ts",
  "props": [
    {
      "name": "aria-activedescendant",
      "type": "string",
      "description": "Identifies the current autocomplete suggestion in custom combobox patterns.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-controls",
      "type": "string",
      "description": "Identifies the element controlled by this input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References one or more elements that describe the input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-description",
      "type": "string",
      "description": "Provides a short hint to assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-disabled",
      "type": "boolean",
      "description": "Indicates whether the element is disabled to assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-expanded",
      "type": "boolean",
      "description": "Indicates whether the input controls an expandable popup.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-haspopup",
      "type": "boolean | \"dialog\" | \"grid\" | \"listbox\" | \"menu\" | \"tree\" | \"true\" | \"false\"",
      "description": "Indicates whether a popup such as a listbox, grid, or dialog is available.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean | \"true\" | \"false\" | \"grammar\" | \"spelling\"",
      "description": "Indicates whether the input has an invalid value.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Explicit accessible label for the outer field region if needed.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References one or more elements that label the input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-readonly",
      "type": "boolean",
      "description": "Indicates whether the input is read-only to assistive technologies.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "description": "Indicates whether user input is required.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "autoComplete",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class names for the outer layout container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the input is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "errorMessage",
      "type": "ReactNode",
      "description": "Validation message associated with the input and announced as an alert.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "errorMessageClassName",
      "type": "string",
      "description": "Additional class names for the validation error message.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "fullWidth",
      "type": "boolean",
      "description": "If true, the input will take up the full width of its container.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "helperText",
      "type": "ReactNode",
      "description": "Supporting text associated with the input through aria-describedby.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "helperTextClassName",
      "type": "string",
      "description": "Additional class names for the helper text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "icon",
      "type": "ComponentType<{ className?: string; \"aria-hidden\"?: boolean; }>",
      "description": "Optional icon component displayed beside the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Additional class names for the icon wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "inputClassName",
      "type": "string",
      "description": "Additional class names for the native input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "invalid",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Optional visible label/title for the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class names for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label. \"top\" | \"left\" | \"right\" | \"bottom\"",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "maxLength",
      "type": "number",
      "description": "Maximum length of the input.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "onChange",
      "type": "((value: string, event: React.ChangeEvent<HTMLInputElement>) => void)",
      "description": "Called when the input value changes. Returns both the current value and the original change event.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "password",
      "type": "boolean",
      "description": "If true, the input behaves as a password field and shows a visibility toggle.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "placeholder",
      "type": "string",
      "description": "Placeholder text shown when the input is empty.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Enter text\""
    },
    {
      "name": "readOnly",
      "type": "boolean",
      "description": "If true, the input is rendered in read-only mode.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Declares the role when this input is used in advanced patterns such as searchbox, combobox, or spinbutton.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the component. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the component. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "size",
      "type": "SizeType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default size (fallback: \"medium\")"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class names for the screen-reader-only text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only. Useful for dynamic status or extra context.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "State of the input. \"success\" | \"error\" | \"warning\" | \"disabled\" | \"\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"text-input\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "togglePasswordClassName",
      "type": "string",
      "description": "Additional class names for the password toggle button.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
