/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const themeSelectPropDocs: GeneratedComponentDoc = {
  "name": "ThemeSelect",
  "interfaceName": "ThemeSelectProps",
  "description": "",
  "sourcePath": "src\\components\\Select\\Select.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional described-by reference.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-description",
      "type": "string",
      "description": "Optional description for screen readers.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-invalid",
      "type": "boolean",
      "description": "Marks the control invalid for assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Optional accessible label for the theme select trigger/input.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional labelled-by reference.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-required",
      "type": "boolean",
      "description": "Marks the control required for assistive technology.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "id",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "name",
      "type": "string",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"\""
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"select\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    }
  ]
};
