/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const timelinePropDocs: GeneratedComponentDoc = {
  "name": "Timeline",
  "interfaceName": "TimelineProps",
  "description": "Props for the Timeline component.",
  "sourcePath": "src\\components\\Timeline\\Timeline.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "Optional aria-describedby for the timeline root.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible label for the timeline. Defaults to \"Timeline\".",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"Timeline\""
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "Optional aria-labelledby for the timeline root. When provided, this should take precedence over \"aria-label\".",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for custom styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "glass",
      "type": "boolean",
      "description": "Applies a translucent frosted-glass treatment using the active theme palette.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "configured default glass setting (fallback: false)"
    },
    {
      "name": "items",
      "type": "TimelineItem[]",
      "description": "Array of timeline items to display.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether timeline item content should display skeleton placeholders. Markers and connector bars remain visible.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "orientation",
      "type": "OrientationType",
      "description": "Orientation of the timeline. \"vertical\" | \"horizontal\"",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"vertical\""
    },
    {
      "name": "role",
      "type": "React.AriaRole",
      "description": "Optional role override for the root element. Defaults to \"list\" when not provided.",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"list\""
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the component. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style of the component. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"timeline\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme to apply for styling. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    }
  ]
};
