/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const toastProviderPropDocs: GeneratedComponentDoc = {
  "name": "ToastProvider",
  "interfaceName": "ToastProviderProps",
  "description": "",
  "sourcePath": "src/components/ToastProvider/ToastProvider.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Content rendered inside the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional CSS class names for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultDuration",
      "type": "number",
      "description": "Default Duration.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "5000"
    },
    {
      "name": "placement",
      "type": "PositionType",
      "description": "Placement.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"topRight\""
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default shadow (fallback: \"light\")"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Test id used to identify the component in tests.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "toastClassName",
      "type": "string",
      "description": "Additional CSS class names for the toast section.",
      "required": false,
      "inherited": false,
      "category": "props"
    }
  ]
};
