/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const toolbarPropDocs: GeneratedComponentDoc = {
  "name": "Toolbar",
  "interfaceName": "ToolbarProps",
  "description": "Props for the `Toolbar` component.",
  "sourcePath": "src/components/Toolbar/Toolbar.types.ts",
  "props": [
    {
      "name": "aria-describedby",
      "type": "string",
      "description": "References one or more elements that describe the toolbar.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "aria-label",
      "type": "string",
      "description": "Accessible name for the toolbar. Prefer this over the legacy `ariaLabel` prop.",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"Toolbar\""
    },
    {
      "name": "aria-labelledby",
      "type": "string",
      "description": "References another element that labels the toolbar. Prefer this over `aria-label` when there is visible text available.",
      "required": false,
      "inherited": false,
      "category": "aria"
    },
    {
      "name": "attachment",
      "type": "AttachmentType",
      "description": "How the toolbar attaches to the viewport or page layout. \"static\" | \"fixed\" | \"sticky\"",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"static\""
    },
    {
      "name": "avatar",
      "type": "{ name?: string; src?: string; size?: SizeType; shape?: \"circle\" | \"square\" | \"rounded\"; theme?: ThemeType; onClick?: (e: MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => void; \"aria-label\"?: string; variant?: VariantType; }",
      "description": "Optional avatar settings displayed at the far right.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "avatarClassName",
      "type": "string",
      "description": "Optional additional class names for the rendered avatar component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "avatarWrapperClassName",
      "type": "string",
      "description": "Optional additional class names for the avatar wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "center",
      "type": "ReactNode",
      "description": "Content to render in the center section, below the title if present.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "centerAriaLabel",
      "type": "string",
      "description": "Optional accessible label for the center section.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Toolbar center section\""
    },
    {
      "name": "centerClassName",
      "type": "string",
      "description": "Optional additional class names for the center section wrapper. Alias for `centerSectionClassName`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "centerContentClassName",
      "type": "string",
      "description": "Optional additional class names for the center section content wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "centerSectionClassName",
      "type": "string",
      "description": "Optional additional class names for the center section wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Optional additional class names for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "left",
      "type": "ReactNode",
      "description": "Content to render in the left section of the toolbar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "leftAriaLabel",
      "type": "string",
      "description": "Optional accessible label for the left section.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Toolbar left section\""
    },
    {
      "name": "leftClassName",
      "type": "string",
      "description": "Optional additional class names for the left section wrapper. Alias for `leftSectionClassName`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "leftContentClassName",
      "type": "string",
      "description": "Optional additional class names for the left section content wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "leftSectionClassName",
      "type": "string",
      "description": "Optional additional class names for the left section wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "right",
      "type": "ReactNode",
      "description": "Content to render in the right section of the toolbar, before the avatar.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rightAriaLabel",
      "type": "string",
      "description": "Optional accessible label for the right section.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Toolbar right section\""
    },
    {
      "name": "rightClassName",
      "type": "string",
      "description": "Optional additional class names for the right section wrapper. Alias for `rightSectionClassName`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rightContentClassName",
      "type": "string",
      "description": "Optional additional class names for the right section content wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rightSectionClassName",
      "type": "string",
      "description": "Optional additional class names for the right section wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "rounding",
      "type": "RoundingType",
      "description": "Rounding of the component. \"none\" | \"small\" | \"medium\" | \"large\" | \"full\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow of the component. \"none\" | \"light\" | \"medium\" | \"strong\" | \"intense\"",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"toolbar\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "The visual theme of the toolbar. \"primary\" | \"secondary\" | \"tertiary\" | \"quaternary\" | \"clear\"",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "string",
      "description": "Optional title displayed in the center section.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleClassName",
      "type": "string",
      "description": "Optional additional class name for the toolbar title element. Useful when consumers need to style the title directly.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleId",
      "type": "string",
      "description": "Optional id used for the rendered title element. Useful for linking the toolbar with `aria-labelledby`.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
