/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const treeViewPropDocs: GeneratedComponentDoc = {
  "name": "TreeView",
  "interfaceName": "TreeViewProps",
  "description": "Props for the TreeView component.",
  "sourcePath": "src/components/TreeView/TreeView.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Fallback content rendered when items are not provided.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class name for fallback child content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "defaultExpandedIds",
      "type": "string[]",
      "description": "Initial expanded node ids for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "defaultSelectedId",
      "type": "string",
      "description": "Initial selected node id for uncontrolled usage.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the tree is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "expandedIds",
      "type": "string[]",
      "description": "Controlled expanded node ids.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "items",
      "type": "TreeViewNode[]",
      "description": "Tree nodes to render.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "label",
      "type": "string",
      "description": "Accessible label for the tree.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Tree\""
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the tree should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "onExpandedChange",
      "type": "((ids: string[]) => void)",
      "description": "Callback fired when expanded nodes change.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "onSelectionChange",
      "type": "((id: string, node: TreeViewNode) => void)",
      "description": "Callback fired when selection changes.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "selectedId",
      "type": "string",
      "description": "Controlled selected node id.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"tree-view\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
