/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types";

export const trendBadgePropDocs: GeneratedComponentDoc = {
  "name": "TrendBadge",
  "interfaceName": "TrendBadgeProps",
  "description": "Props for the TrendBadge component.",
  "sourcePath": "src\\components\\TrendBadge\\TrendBadge.types.ts",
  "props": [
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "direction",
      "type": "\"up\" | \"down\" | \"flat\"",
      "description": "Explicit trend direction. When omitted, direction is inferred from value and previousValue.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Visible metric label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "positiveIsUp",
      "type": "boolean",
      "description": "Whether a higher value should be treated as positive.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "prefix",
      "type": "ReactNode",
      "description": "Prefix rendered before the numeric value.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "previousValue",
      "type": "number",
      "description": "Previous value used to calculate the trend.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "showDelta",
      "type": "boolean",
      "description": "Whether to show the calculated delta instead of the current value.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "suffix",
      "type": "ReactNode",
      "description": "Suffix rendered after the numeric value.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"trend-badge\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme class used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "\"primary\""
    },
    {
      "name": "value",
      "type": "number",
      "description": "Current numeric value.",
      "required": true,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "valueFormatter",
      "type": "((value: number) => ReactNode)",
      "description": "Formatter for the value or delta.",
      "required": false,
      "inherited": false,
      "category": "events",
      "defaultValue": "formatDefaultValue"
    }
  ]
};
