/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/generate-component-docs.cjs
 */

import type { GeneratedComponentDoc } from "./types.js";

export const validationSummaryPropDocs: GeneratedComponentDoc = {
  "name": "ValidationSummary",
  "interfaceName": "ValidationSummaryProps",
  "description": "Props for the ValidationSummary component.",
  "sourcePath": "src/components/ValidationSummary/ValidationSummary.types.ts",
  "props": [
    {
      "name": "children",
      "type": "ReactNode",
      "description": "Main content rendered inside the component after the generated validation list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "className",
      "type": "string",
      "description": "Additional class name for the component root.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "containerClassName",
      "type": "string",
      "description": "Additional class name for the outer label/component container.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "contentClassName",
      "type": "string",
      "description": "Additional class name for the content area.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "data-testid",
      "type": "string",
      "description": "Backward-compatible alias for test ID attributes.",
      "required": false,
      "inherited": false,
      "category": "testing"
    },
    {
      "name": "description",
      "type": "ReactNode",
      "description": "Supporting text rendered beneath the title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "descriptionClassName",
      "type": "string",
      "description": "Additional class name for the description.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "disabled",
      "type": "boolean",
      "description": "Whether the component is disabled.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "emptyClassName",
      "type": "string",
      "description": "Additional class name for empty-state text.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "emptyMessage",
      "type": "ReactNode",
      "description": "Message rendered when there are no validation items and hideWhenEmpty is false.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "focusOnMount",
      "type": "boolean",
      "description": "Whether the summary should focus itself when validation items are present.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "focusable",
      "type": "boolean",
      "description": "Whether the summary should be focusable for programmatic focus.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "headerClassName",
      "type": "string",
      "description": "Additional class name for the title/icon header row.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "hideWhenEmpty",
      "type": "boolean",
      "description": "Whether nothing should render when there are no items and no children.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "true"
    },
    {
      "name": "icon",
      "type": "ReactElement<unknown, string | JSXElementConstructor<any>>",
      "description": "Optional icon rendered before the summary title. Accepts Font Awesome icons, SVG elements, or custom React elements.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconAriaLabel",
      "type": "string",
      "description": "Accessible label for the icon when it communicates meaning. If omitted, the icon is treated as decorative.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "iconClassName",
      "type": "string",
      "description": "Additional class name for the icon wrapper.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "itemClassName",
      "type": "string",
      "description": "Additional class name for each list item.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "items",
      "type": "(string | ValidationSummaryItem)[]",
      "description": "Validation items rendered in the summary list.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "[]"
    },
    {
      "name": "label",
      "type": "ReactNode",
      "description": "Optional visible label for the component.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelClassName",
      "type": "string",
      "description": "Additional class name for the visible label.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "labelPosition",
      "type": "LabelPositionType",
      "description": "Position of the label relative to the component.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"top\""
    },
    {
      "name": "linkClassName",
      "type": "string",
      "description": "Additional class name for validation links.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "listClassName",
      "type": "string",
      "description": "Additional class name for the list.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "listLabel",
      "type": "string",
      "description": "Accessible label for the validation issue list.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Validation issues\""
    },
    {
      "name": "loading",
      "type": "boolean",
      "description": "Whether the component should display a loading state.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "false"
    },
    {
      "name": "loadingMessage",
      "type": "ReactNode",
      "description": "Accessible loading message rendered while loading is true.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"Checking validation\""
    },
    {
      "name": "onItemClick",
      "type": "((item: ValidationSummaryItem, index: number) => void)",
      "description": "Callback fired when a validation issue is selected.",
      "required": false,
      "inherited": false,
      "category": "events"
    },
    {
      "name": "role",
      "type": "\"alert\" | \"region\" | \"status\"",
      "description": "Role applied to the validation summary root.",
      "required": false,
      "inherited": false,
      "category": "aria",
      "defaultValue": "\"alert\""
    },
    {
      "name": "rounding",
      "type": "RoundableRoundingType",
      "description": "Rounding style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default rounding (fallback: \"medium\")"
    },
    {
      "name": "shadow",
      "type": "ShadowType",
      "description": "Shadow style for the component.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "srOnlyClassName",
      "type": "string",
      "description": "Additional class name for screen-reader-only content.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "srOnlyText",
      "type": "ReactNode",
      "description": "Optional content rendered for assistive technologies only.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "state",
      "type": "StateType",
      "description": "Visual state for styling.",
      "required": false,
      "inherited": false,
      "category": "styling"
    },
    {
      "name": "testId",
      "type": "string",
      "description": "Optional test ID for testing frameworks.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "dataTestId ?? \"validation-summary\""
    },
    {
      "name": "theme",
      "type": "ThemeType",
      "description": "Theme used for styling.",
      "required": false,
      "inherited": false,
      "category": "styling",
      "defaultValue": "configured default theme (fallback: \"primary\")"
    },
    {
      "name": "title",
      "type": "ReactNode",
      "description": "Summary heading rendered inside the alert.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "titleAs",
      "type": "\"h2\" | \"h3\" | \"h4\" | \"h5\" | \"h6\"",
      "description": "Heading element used for the summary title.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "\"h2\""
    },
    {
      "name": "titleClassName",
      "type": "string",
      "description": "Additional class name for the title.",
      "required": false,
      "inherited": false,
      "category": "props"
    },
    {
      "name": "variant",
      "type": "VariantType",
      "description": "Surface treatment; glassOutline combines glass and outline.",
      "required": false,
      "inherited": false,
      "category": "props",
      "defaultValue": "getDefaultVariant()"
    }
  ]
};
